---
# vars file for win_firewall_rule
ansible_ssh_user: devopsadmin
ansible_ssh_pass: P@ssw0rd4SOLEX30
ansible_ssh_port: 5986
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore

