- name: ensure domain
  ansible.windows.win_domain:
    dns_domain_name: "{{ domain.dns_domain_name }}"
    domain_netbios_name: "{{ domain.domain_netbios_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
    sysvol_path: "{{ domain.sysvol_path }}"
    database_path: "{{ domain.database_path }}"
  register: adDomain

- name: reboot
  win_reboot:  
  when : adDomain.reboot_required